<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ItemEdit extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'disclosure' => 'required',
            'file' => 'required|mimes:pdf',
        ];
    }

    public function messages()
    {
        return ([
            'disclosure.required' => 'É necessário selecionar a data de divulgação!',
            'file.mimes' => 'Somente arquivo do tipo PDF é aceito!',
            'file.required' => 'O campo anexo é obrigatório'
        ]); // TODO: Change the autogenerated stub
    }
}

